// import { OrderStatus } from "@model/order.model";

export const StatusCode = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

// export const validTransitions: Record<OrderStatus, OrderStatus[]> = {
//   [OrderStatus.PENDING]: [OrderStatus.CONFIRMED, OrderStatus.CANCELED],
//   [OrderStatus.CONFIRMED]: [OrderStatus.SHIPPING, OrderStatus.CANCELED],
//   [OrderStatus.SHIPPING]: [OrderStatus.COMPLETED, OrderStatus.FAILED],
//   [OrderStatus.COMPLETED]: [],
//   [OrderStatus.CANCELED]: [],
//   [OrderStatus.RETURNED]: [
//     OrderStatus.REFUNDED,
//     OrderStatus.PARTIALLY_REFUNDED,
//   ],
//   [OrderStatus.FAILED]: [OrderStatus.RETURNED],
//   [OrderStatus.AWAITING_PAYMENT]: [OrderStatus.PENDING],
//   [OrderStatus.PROCESSING]: [OrderStatus.OUT_FOR_DELIVERY],
//   [OrderStatus.OUT_FOR_DELIVERY]: [OrderStatus.COMPLETED, OrderStatus.FAILED],
//   [OrderStatus.REFUNDED]: [],
//   [OrderStatus.PARTIALLY_REFUNDED]: [],
// };

export const Messages = {
  category: {
    successGetList: "Lấy danh sách danh mục thành công",
    successGetDetail: "Lấy chi tiết danh mục thành công",
    exitCategory: "Danh mục đã tồn tại",
    successCreate: "Tạo danh mục thành công",
    successUpdate: "Cập nhật danh mục thành công",
    successLock: "Khoá danh mục thành công",
    successUnLock: "Mở khoá danh mục thành công",
    notFound: "Không tìm thấy danh mục",
  },

  product: {
    successGetList: "Lấy danh sách sản phẩm thành công",
    successGetDetail: "Lấy chi tiết sản phẩm thành công",
    exitProduct: "Sản phẩm đã tồn tại",
    successCreate: "Tạo sản phẩm thành công",
    successUpdate: "Cập nhật sản phẩm thành công",
    successLock: "Khoá sản phẩm thành công",
    successUnLock: "Mở Khoá sản phẩm thành công",
    notFound: "Không tìm thấy sản phẩm",
  },

  productPromotion: {
    successGetList: "Lấy danh sách khuyến mãi sản phẩm thành công",
    successGetDetail: "Lấy chi tiết khuyến mãi sản phẩm thành công",
    exitProductPromotion: "Khuyến mãi sản phẩm đã tồn tại",
    successCreate: "Tạo khuyến mãi sản phẩm thành công",
    successUpdate: "Cập nhật khuyến mãi sản phẩm thành công",
    successLock: "Khoá khuyến mãi sản phẩm thành công",
    successUnlock: "Mở khoá khuyến mãi sản phẩm thành công",
    invalid: "Khuyến mãi không hợp lệ hoặc đã hết hạn sử dụng",
    valid: "Khuyến mãi hợp lệ",
    notFound: "Không tìm thấy khuyến mãi sản phẩm",
  },

  publishingCompany: {
    successGetList: "Lấy danh sách nhà cung cấp thành công",
    successGetDetail: "Lấy chi tiết nhà cung cấp thành công",
    exitPublishingCompany: "Nhà cung cấp đã tồn tại",
    missingName: "Vui lòng nhập tên nhà cung cấp",
    successCreate: "Tạo nhà cung cấp thành công",
    successUpdate: "Cập nhật nhà cung cấp thành công",
    successLock: "Khoá nhà cung cấp thành công",
    successUnlock: "Mở khoá nhà cung cấp thành công",
    notFound: "Không tìm thấy nhà cung cấp",
  },

  discount: {
    successGetList: "Lấy danh sách mã giảm giá thành công",
    successGetDetail: "Lấy chi tiết mã giảm giá thành công",
    exitDiscount: "Mã giảm giá đã tồn tại",
    successCreate: "Tạo mã giảm giá thành công",
    successUpdate: "Cập nhật mã giảm giá thành công",
    successLock: "Khoá mã giảm giá thành công",
    successUnlock: "Mở khoá mã giảm giá thành công",
    invalid: "Mã giảm giá không hợp lệ hoặc đã hết hạn sử dụng",
    valid: "Mã giảm giá hợp lệ",
    notFound: "Không tìm thấy mã giảm giá",
  },

  cart: {
    successGetList: "Lấy danh sách giỏ hàng thành công",
    successGetByUser: "Lấy giỏ hàng của user thành công",
    successAddToCart: "Thêm sản phẩm vào giỏ hàng thành công",
    successIncrease: "Tăng số lượng sản phẩm thành công.",
    successDecrease: "Giảm số lượng sản phẩm thành công.",
    successRemove: "Xóa sản phẩm khỏi giỏ hàng thành công.",
    notFound: "Không tìm thấy giỏ hàng",
  },

  deliveryAddress: {
    successGetList: "Lấy danh sách địa chỉ giao hàng thành công",
    successGetByUser: "Lấy địa chỉ giao hàng của user thành công",
    successAdd: "Thêm địa chỉ giao hàng thành công",
    successUpdate: "Cập nhật địa chỉ giao hàng thành công",
    successRemove: "Xóa sản phẩm khỏi địa chỉ giao hàng thành công.",
    notFound: "Không tìm thấy địa chỉ giao hàng",
  },

  order: {
    successGetList: "Lấy danh sách đơn hàng thành công",
    successGetDetail: "Lấy chi tiết đơn hàng thành công",
    successGetByUser: "Lấy chi tiết đơn hàng theo user thành công",
    successGetByUserAndStatus:
      "Lấy chi tiết đơn hàng theo user và trạng thái thành công",
    successOrdering: "Đặt hàng thành công",
    successConfirm: "Xác nhận đơn hàng thành công",
    cannotConfirm: "Không thể xác nhận đơn hàng",
    successProcessing: "Đơn hàng đang được xử lý",
    successAwaitingPayment: "Đơn hàng đang chờ thanh toán",
    successChangeDelivery: "Đơn hàng sẽ sớm được giao",
    successOutForDelivery: "Đơn hàng đang giao tới",
    successDeliver: "Giao hàng thành công",
    successComplete: "Đơn hàng đã được hoàn thành",
    cannotComplete: "Không thể hoàn thành đơn hàng",
    successCancel: "Đơn hàng đã bị huỷ",
    cannotCancel: "Không thể huỷ đơn hàng",
    successReturn: "Trả hàng thành công",
    successRefund: "Hoàn tiền thành công",
    successFail: "Đơn hàng giao thất bại",
    notFound: "Không tìm thấy đơn hàng",
    invalidStatusChange: "Không thể chuyển sang trạng thái này",
    successUpdateStatus: "Cập nhật trạng thái đơn hàng thành công",
  },

  orderDetail: {
    successGetList: "Lấy danh sách chi tiết đơn hàng thành công",
    successGetDetail: "Lấy chi tiết đơn hàng thành công",
    successCreate: "Tạo chi tiết đơn hàng thành công",
    successUpdate: "Cập nhật chi tiết đơn hàng thành công",
    successDelete: "Xóa chi tiết đơn hàng thành công",
    notFound: "Không tìm thấy chi tiết đơn hàng",
  },

  role: {
    successGetList: "Lấy danh sách quyền thành công",
  },

  user: {
    successGetList: "Lấy danh sách tài khoản thành công",
    successGetDetail: "Lấy chi tiết tài khoản thành công",
    successLock: "Khoá tài khoản thành công",
    errorLock: "Lỗi khi khoá tài khoản",
    successUnlock: "Mở khoá tài khoản thành công",
    errorUnlock: "Lỗi khi mở khoá tài khoản",
    invalidRoleIds: "Danh sách quyền không hợp lệ",
    invalidRoleId: "ID quyền không hợp lệ",
    successSetRoles: "Cập nhật quyền tài khoản thành công",
    errorSetRoles: "Lỗi khi cập nhật quyền tài khoản",
    successSearch: "Tìm kiếm tài khoản thành công",
    successResetPassword: "Đặt lại mật khẩu thành công",
    errorResetPassword: "Lỗi khi đặt lại mật khẩu",
    successChangeInfo: "Thay đổi thông tin cá nhân thành công",
    noChangeInfo: "Không có thông tin cá nhân được thay đổi",
    notFound: "Không tìm thấy tài khoản",
  },

  setting: {
    successGetListImage: "Lấy danh sách ảnh thành công",
    errorGetListImage: "Lỗi khi lấy danh sách ảnh",
    successUpdate: "Cập nhật ảnh thành công",
    errorUpdate: "Lỗi khi cập nhật ảnh",
    missingImage: "Vui lòng chọn ảnh",
  },

  menu: {
    successGetList: "Lấy danh sách menu thành công",
    successGetDetail: "Lấy chi tiết menu thành công",
    successCreate: "Tạo menu thành công",
    successUpdate: "Cập nhật menu thành công",
    successDelete: "Xóa menu thành công",
    invalidMenuIds: "Có MenuIDs không hợp lệ hoặc không tồn tại",
    noiExitMenuInUser: "User chưa có Menu để truy cập",
    exitMenuInUser: "Một hoặc một số menu đã tồn tại trong User",
    successSetMenuForUser: "Cấp quyền truy cập menu thành công",
    successUnSetMenuForUser: "Lấy lại quyền truy cập menu thành công",
    notFound: "Không tìm thấy menu trong danh sách",
  },

  auth: {
    notExitAccount: "Tài khoản không tồn tại",
    lockedAccount: "Tài khoản đã bị khoá",
    invalidPassword: "Mật khẩu không hợp lệ",
    wrongPassword: "Mật khẩu không chính xác",
    loginFail: "Đăng nhập thất bại",
    loginSuccess: "Đăng nhập thành công",

    exitEmail: "Email đã được sử dụng",
    invalidEmail: "Email không hợp lệ",
    exitPhone: "Số điện thoại đã được sử dụng",
    registerSuccess: "Đăng ký tài khoản thành công",
    registerError: "Lỗi khi đăng ký tài khoản",
    logoutSuccess: "Đăng xuất thành công",

    wrongOldPassWord: "Mật khẩu cũ không chính xác",
    newPasswordCannotBeOldPassword: "Mật khẩu mới phải khác mật khẩu cũ",
    confirmPassword: "Vui lòng xác nhận mật khẩu",
    successChangePassword: "Thay đổi mật khẩu thành công",
    errorChangePassword: "Lỗi khi thay đổi mật khẩu",

    successSendResetLink: "Gửi link lấy lại mật khẩu thành công",

    successCreateACcount: "Tạo mới tài khoản thành công",
    errorCreateAccount: "Lỗi khi tạo mới tài khoản",

    notProvidedToken: "Chưa cung cấp token",
    invalidToken: "Token không hợp lệ",
    unauthorized: "Bạn không có quyền truy cập",
    onlyAdminAccess: "Chỉ có Adminstrator đã đăng nhập mới có quyền truy cập",
    onlyUserAccess: "Chỉ có User đã đăng nhập mới có quyền truy cập",
    tokenExpired: "Token đã hết hạn",
    refreshTokenInvalid: "Refresh token không hợp lệ hoặc đã hết hạn",
    noJWTSECRET: "Biến môi trường JWT_SECRET chưa được cấu hình",
    successRefreshToken: "Làm mới token thành công",
    errorRefreshToken: "Lỗi khi làm mới token",
  },

  common: {
    missingFields: "Vui lòng nhập đầy đủ thông tin",
    unexpectedError: "Đã xảy ra lỗi, vui lòng thử lại sau",
    forbidden: "Bạn không có quyền thực hiện hành động này",
    failedToGet: "Lỗi khi lấy dữ liệu",
    invalidID: "ID không hợp lệ",
    invalidSlug: "Slug không hợp lệ",
    missingID: "Thiếu ID trong tham số URL",
    missingSlug: "Thiếu Slug trong tham số URL",
    missingEmail: "Thiếu email trong tham số URL",
    missingName: "Thiếu tên tài khoản",
    missingImage: "Vui lòng chọn ảnh",
    under10MB: "Dung lượng ảnh phải nhỏ hơn 10MB",
    createDirectoryError: "Lỗi khi tạo thư mục",
    uploadImageError: "Lỗi khi tải ảnh lên",
    uploadImgSuccess: "Tải ảnh lên thành công",
  },
};
